language: python

dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
  # Also test pypy
  - "pypy"
  - "pypy3"

install: 
  - pip install -r requirements.txt
  - pip install pypandoc

addons:
  apt_packages:
    - pandoc  # Required to convert the README to a Pypi description

addons:
  apt_packages:
    - pandoc  # Required to convert the README to a Pypi description

# Run the unit tests
script:
  - python -m pytest -v
  - pip install .
  - archiver --help
